"""Default v0 rules for the Scheme B executable rule engine."""
from __future__ import annotations

from refute_b_v2.rules import RefutationRule, RuleSet


def default_rule_set() -> RuleSet:
    return RuleSet(rules=(
        RefutationRule(
            id="cpu.container_cpu_required",
            reason_buckets=("cpu",),
            evidence_query="container_kpi_anomalous",
            query_args={"kpi_bucket": "cpu"},
            rule_type="hard",
            support_if="matched",
            refute_if="not_matched",
            confidence=1.0,
            group="round_1_cheap_metric",
            description="CPU roots should show service-local CPU/JVM CPU anomaly.",
        ),
        RefutationRule(
            id="disk.disk_io_required",
            reason_buckets=("disk_io",),
            evidence_query="node_kpi_anomalous",
            query_args={"kpi_bucket": "disk"},
            rule_type="hard",
            support_if="matched",
            refute_if="not_matched",
            confidence=1.0,
            group="round_1_cheap_metric",
            description="Disk I/O roots should show node/container disk evidence.",
        ),
        RefutationRule(
            id="filesystem.capacity_required",
            reason_buckets=("filesystem",),
            evidence_query="node_kpi_anomalous",
            query_args={"kpi_bucket": "filesystem"},
            rule_type="hard",
            support_if="matched",
            refute_if="not_matched",
            confidence=1.0,
            group="round_1_cheap_metric",
            description="Disk space roots should show filesystem capacity/inode evidence.",
        ),
        RefutationRule(
            id="memory.container_memory_anomaly",
            reason_buckets=("memory",),
            reason_names=("high memory usage",),
            evidence_query="container_kpi_anomalous",
            query_args={"kpi_bucket": "memory"},
            rule_type="soft",
            support_if="matched",
            refute_if="",
            confidence=0.5,
            group="round_1_cheap_metric",
            description="High memory usage can be supported by service-local memory KPI evidence; absence is not enough to refute in v0.",
        ),
        RefutationRule(
            id="memory.jvm_oom_log_required",
            reason_buckets=("jvm_oom",),
            reason_names=("JVM Out of Memory (OOM) Heap",),
            evidence_query="log_keyword_match",
            query_args={"keywords": ["OutOfMemoryError", "Java heap space", "GC overhead", "Full GC"]},
            rule_type="hard",
            support_if="matched",
            refute_if="",
            confidence=1.0,
            group="round_3_log_blind",
            description="Fatal OOM/GC logs are strong OOM support; absence is not enough to refute in Bank v0.",
        ),
        RefutationRule(
            id="memory.jvm_heap_plus_gc_log",
            reason_buckets=("jvm_oom",),
            reason_names=("JVM Out of Memory (OOM) Heap",),
            evidence_query="all_of",
            query_args={
                "queries": [
                    {"name": "container_kpi_anomalous", "args": {"kpi_bucket": "memory"}},
                    {"name": "log_keyword_match", "args": {"keywords": ["Full GC", "OutOfMemoryError", "GC overhead"]}},
                ]
            },
            rule_type="hard",
            support_if="matched",
            refute_if="",
            confidence=1.0,
            group="round_3_log_blind",
            description="JVM heap and fatal GC/OOM logs together are strong OOM support.",
        ),
        RefutationRule(
            id="memory.jvm_heap_kpi",
            reason_buckets=("jvm_oom",),
            reason_names=("JVM Out of Memory (OOM) Heap",),
            evidence_query="specialty_kpi_anomalous",
            query_args={"kpi_bucket": "jvm_heap"},
            rule_type="soft",
            support_if="matched",
            refute_if="",
            confidence=0.5,
            group="round_1_cheap_metric",
            description="JVM heap KPI supports OOM but absence is not refutation.",
        ),
        RefutationRule(
            id="memory.redis_memory_kpi",
            reason_buckets=("memory",),
            reason_names=("high memory usage",),
            evidence_query="specialty_kpi_anomalous",
            query_args={"kpi_bucket": "redis_memory"},
            rule_type="soft",
            support_if="matched",
            refute_if="",
            confidence=0.5,
            group="round_1_cheap_metric",
            description="Redis memory KPIs support high memory usage for Redis candidates.",
        ),
        RefutationRule(
            id="memory.mysql_memory_kpi",
            reason_buckets=("memory",),
            reason_names=("high memory usage",),
            evidence_query="specialty_kpi_anomalous",
            query_args={"kpi_bucket": "mysql_memory"},
            rule_type="soft",
            support_if="matched",
            refute_if="",
            confidence=0.5,
            group="round_1_cheap_metric",
            description="Mysql memory KPIs support high memory usage for Mysql candidates.",
        ),
        RefutationRule(
            id="network_latency.trace_slow_edge",
            reason_buckets=("network_latency",),
            evidence_query="trace_slow_edge",
            rule_type="soft",
            support_if="matched",
            refute_if="",
            confidence=0.5,
            group="round_2_trace_topology",
            description="Slow trace edges support latency involvement but do not prove root cause.",
        ),
        RefutationRule(
            id="network_latency.trace_first_anomalous",
            reason_buckets=("network_latency",),
            evidence_query="trace_first_anomalous_service",
            rule_type="soft",
            support_if="matched",
            refute_if="",
            confidence=0.5,
            group="round_2_trace_topology",
            description="Being the first anomalous trace service supports latency root-cause suspicion.",
        ),
        RefutationRule(
            id="network_latency.trace_upstream_source",
            reason_buckets=("network_latency",),
            evidence_query="trace_propagation_role",
            query_args={"roles": ["upstream_source"]},
            rule_type="soft",
            support_if="matched",
            refute_if="",
            confidence=0.5,
            group="round_2_trace_topology",
            description="An upstream source role on anomalous trace edges supports latency root-cause suspicion.",
        ),
        RefutationRule(
            id="network_latency.timeout_log",
            reason_buckets=("network_latency",),
            evidence_query="log_keyword_match",
            query_args={"keywords": ["timeout", "timed out", "read timeout", "connect timeout", "upstream timed out"]},
            rule_type="soft",
            support_if="matched",
            refute_if="",
            confidence=0.5,
            group="round_3_log_blind",
            description="Timeout logs support latency involvement.",
        ),
        RefutationRule(
            id="network_packet_loss.retry_reset_log",
            reason_buckets=("network_packet_loss",),
            evidence_query="log_keyword_match",
            query_args={"keywords": ["retry", "connection reset", "reset by peer", "broken pipe", "connection aborted"]},
            rule_type="soft",
            support_if="matched",
            refute_if="",
            confidence=0.5,
            group="round_3_log_blind",
            description="Retry/reset/broken-pipe logs support packet-loss-like failure.",
        ),
        RefutationRule(
            id="network_packet_loss.edge_count_drop",
            reason_buckets=("network_packet_loss",),
            evidence_query="trace_edge_count_drop",
            rule_type="soft",
            support_if="matched",
            refute_if="",
            confidence=0.5,
            group="round_2_trace_topology",
            description="Trace edge count drop supports packet-loss-like failure.",
        ),
        RefutationRule(
            id="network_packet_loss.trace_upstream_source",
            reason_buckets=("network_packet_loss",),
            evidence_query="trace_propagation_role",
            query_args={"roles": ["upstream_source"]},
            rule_type="soft",
            support_if="matched",
            refute_if="",
            confidence=0.5,
            group="round_2_trace_topology",
            description="An upstream source role on dropped/slow trace edges supports packet-loss root-cause suspicion.",
        ),
        RefutationRule(
            id="network_packet_loss.network_error_kpi",
            reason_buckets=("network_packet_loss",),
            evidence_query="container_kpi_anomalous",
            query_args={"kpi_bucket": "network"},
            rule_type="soft",
            support_if="matched",
            refute_if="",
            confidence=0.5,
            group="round_1_cheap_metric",
            description="Network/TCP error KPI supports packet-loss-like failure after audit.",
        ),
    ))
