from __future__ import annotations

import hashlib
import json
from pathlib import Path
from types import SimpleNamespace

import pytest

from prism_v3.leakage_guard import (
    UnsafeInferenceQueryError,
    UntrustedArtifactError,
    assert_inference_query_safe,
    build_query_id,
    validate_external_artifact,
)


def _query(**overrides):
    payload = {
        "system": "Bank",
        "sub_system": "",
        "task_index": "task_1",
        "query_index": 7,
        "ground_truth": None,
        "scoring_points": [],
    }
    payload.update(overrides)
    return SimpleNamespace(**payload)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _write_manifest(path: Path, **overrides) -> None:
    payload = {
        "artifact_type": "no_leak_ltr_scores",
        "feature_pipeline_version": "noise_lab_no_gt_v1",
        "generated_without_gt": True,
        "allowed_anchor_sources": ["public_query_window"],
        "fit_query_ids": [],
        "fit_dates": [],
        "fit_systems": ["Bank"],
        "git_commit": "test",
        "artifact_sha256": _sha256(path),
        "metadata": {},
    }
    payload.update(overrides)
    Path(f"{path}.manifest.json").write_text(json.dumps(payload), encoding="utf-8")


def test_inference_query_rejects_ground_truth() -> None:
    with pytest.raises(UnsafeInferenceQueryError, match="ground_truth"):
        assert_inference_query_safe(_query(ground_truth=object()))


def test_inference_query_rejects_scoring_points() -> None:
    with pytest.raises(UnsafeInferenceQueryError, match="scoring_points"):
        assert_inference_query_safe(_query(scoring_points=[object()]))


def test_certified_artifact_is_accepted(tmp_path: Path) -> None:
    artifact = tmp_path / "scores.csv"
    artifact.write_text("query_index,task_index,object_id,ltr_score\n7,task_1,a,1.0\n", encoding="utf-8")
    _write_manifest(artifact)
    manifest = validate_external_artifact(
        str(artifact), current_query_id=build_query_id(_query())
    )
    assert manifest.generated_without_gt is True


def test_legacy_artifact_without_manifest_is_rejected(tmp_path: Path) -> None:
    artifact = tmp_path / "legacy.csv"
    artifact.write_text("query_index,task_index,object_id,ltr_score\n7,task_1,a,1.0\n", encoding="utf-8")
    with pytest.raises(UntrustedArtifactError, match="missing artifact manifest"):
        validate_external_artifact(str(artifact), current_query_id=build_query_id(_query()))


def test_artifact_generated_with_gt_is_rejected(tmp_path: Path) -> None:
    artifact = tmp_path / "unsafe.csv"
    artifact.write_text("query_index,task_index,object_id,ltr_score\n7,task_1,a,1.0\n", encoding="utf-8")
    _write_manifest(artifact, generated_without_gt=False)
    with pytest.raises(UntrustedArtifactError, match="not generated by a no-GT pipeline"):
        validate_external_artifact(str(artifact), current_query_id=build_query_id(_query()))


def test_current_query_must_be_out_of_fold(tmp_path: Path) -> None:
    artifact = tmp_path / "in_fold.csv"
    artifact.write_text("query_index,task_index,object_id,ltr_score\n7,task_1,a,1.0\n", encoding="utf-8")
    query_id = build_query_id(_query())
    _write_manifest(artifact, fit_query_ids=[query_id])
    with pytest.raises(UntrustedArtifactError, match="fit_query_ids"):
        validate_external_artifact(str(artifact), current_query_id=query_id)


def test_artifact_checksum_must_match(tmp_path: Path) -> None:
    artifact = tmp_path / "tampered.csv"
    artifact.write_text("query_index,task_index,object_id,ltr_score\n7,task_1,a,1.0\n", encoding="utf-8")
    _write_manifest(artifact)
    artifact.write_text("tampered\n", encoding="utf-8")
    with pytest.raises(UntrustedArtifactError, match="sha256 mismatch"):
        validate_external_artifact(str(artifact), current_query_id=build_query_id(_query()))
